{% set name = "openmm-setup" %}
{% set version = "1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/openmm/openmm-setup/archive/v{{ version }}.tar.gz
  sha256: 1b6a1b3066418a9266b9fbf93cff0dfc2cb11c2875943770578c35d28691432c

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps
  entry_points:
    - openmm-setup = openmmsetup.openmmsetup:main

requirements:
  host:
    - python
    - pip
  run:
    - python >=3.6
    - flask
    - openmm >=7.5
    - pdbfixer >=1.5

test:
  imports:
    - openmmsetup

about:
  home: http://openmm.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: User interface for preparing and running OpenMM simulations
  description: |
    This is an application for configuring and running simulations with OpenMM.
    It provides a graphical interface for selecting input files, cleaning up PDB structures,
    and setting simulation options. It can then either save a script for running the
    simulation later, or directly run the simulation itself.
  doc_url: http://docs.openmm.org/
  dev_url: https://github.com/openmm/openmm-setup

extra:
  recipe-maintainers:
    - jaimergp
    - peastman
    - jchodera
