{% set name = "openmm-setup" %}
{% set version = "1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/openmm/{{ name }}.git
  git_rev: "0916b60"

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv --no-deps
  entry_points:
    - openmm-setup = openmmsetup.openmmsetup:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - flask
    - openmm >=8.1
    - pdbfixer >=1.5

test:
  requires:
    - python {{ python_min }}
  imports:
    - openmmsetup

about:
  home: http://openmm.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: User interface for preparing and running OpenMM simulations
  description: |
    This is an application for configuring and running simulations with OpenMM.
    It provides a graphical interface for selecting input files, cleaning up PDB structures,
    and setting simulation options. It can then either save a script for running the
    simulation later, or directly run the simulation itself.
  doc_url: http://docs.openmm.org/
  dev_url: https://github.com/openmm/openmm-setup

extra:
  recipe-maintainers:
    - jaimergp
    - peastman
    - jchodera
